[project]
name = "tobien_vat_checker"
authors = [
    { name = "phamos.eu", email = "support@phamos.eu"}
]
description = "EU-USt-IdNr. Pruefung (VIES) fuer Sales-Belege in ERPNext v15"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe~=15.0.0" # Installed and managed by bench.
    "requests"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"

[tool.bench.dev-dependencies]
